enum TodoActionTypes {
	GET_ITEM_LIST = 'GET_ITEM_LIST',
	ADD_ITEM = 'ADD_ITEM',
	DELETE_ITEM = 'DELETE_ITEM',
	DELETE_COMPLETED_ITEMS = 'DELETE_COMPLETED_ITEMS',
	TOGGLE_ALL_ITEMS = 'TOGGLE_ALL_ITEMS',
	CHANGE_ITEM_CHECK = 'CHANGE_ITEM_CHECK',
	CHANGE_ITEM_VALUE = 'CHANGE_ITEM_VALUE',
}

export default TodoActionTypes;
